name: Pyre-Check

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  pyre:
    # Name the Job
    name: Pyre Check
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install async-generator pyre-check-nightly click dataclasses-json libcst psutil pywatchman tabulate testslide typing_extensions
          python -m pip install cython
          python -m pip install flask flask_cors graphql-core typing_inspect
          VERSION=$(grep "version" .pyre_configuration | sed -n -e 's/.*\(0\.0\.[0-9]*\).*/\1/p')
          python -m pip install pyre-check-nightly==$VERSION
      - name: Run Pyre
        run: |
          pyre check
